# apiVersion: v1
# kind: ReplicationController
# metadata:
#   name: my-rep-ctrl
#   labels:
#     app: myapp
#     run: nginx
# spec:
#   replicas: 3
#   template:  # Pod definition template
#     metadata:
#       name: myapp-pod
#       labels:
#         run: nginx
#     spec:
#       containers:
#         - name: myapp
#           image: nginx
#           ports:
#             - containerPort: 80
--- 

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  namespace: application
  labels:
    app: myapp
    run: nginx
    env: dev
spec:
  # modify replicas according to your case
  replicas: 4
  selector:    # Required field in Replicaset
    matchExpressions:
      - key: app 
        operator: In 
        values:
          - myapp
          - myapp2
    # matchLabels:
    #   run: nginx
    #   app: myapp
  template:
    metadata:
      labels:
        run: nginx
        app: myapp
        env: dev
    spec:
      containers:
      - name: myapp
        image: nginx
        ports:
        - name: web
          containerPort:  80
          protocol: TCP
        env:
        - name: NGX_VERSION
          value: 1.16.1
        
# --- 

# apiVersion: v1
# kind: Pod
# metadata:
#   name: jjtech-pod
#   namespace: application
#   labels:
#     app: myapp
#     run: nginx
# spec:
#   containers:
#   - name: myapp
#     image: nginx
#     resources:
#       limits:
#         cpu: 200m
#         memory: 500Mi
#       requests:
#         cpu: 100m
#         memory: 200Mi
#     ports:
#     - containerPort:  80
#       name:  http
