apiVersion: v1
kind: Pod
metadata:
  name: "tower-pod2"
  namespace: jjtech-project
  labels:
    app: "tower"
spec:
  containers:
  - name: tower-container
    image: "nginx"
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
    