apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      #nodeName: ip-10-20-109-206.ec2.internal
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: data-volume
              mountPath: /opt # Mount path inside the container
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: local-pvc  # Name of your PersistentVolumeClaim