--- 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc
  namespace: application
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage
  #volumeName: example-pv