# This ClusterRole allows users assigned with this role to perform get, list, watch, and create operations on pods.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-reader-creator-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  # - apiGroups: ["apps"]
  #   resources: ["deployments", "daemonsets",statefulsets]
  #   verbs: ["get", "list", "watch", "create", "update", "delete"]
