apiVersion: v1
kind: Pod
metadata:
  name: "myapp2"
  namespace: default
  labels:
    app: "myapp"
spec:
  containers:
  - name: myapp
    image: deekshithsn/k8s-deployment-strategies 
    ports:
    - containerPort:  8080
      name:  http
    env:
    - name: VERSION
      valueFrom:
        configMapKeyRef:
          name: jjtech-cm
          key: app-version
    volumeMounts:
        - name: app-version
          mountPath: /opt
  volumes:
    - name: app-version
      configMap:
        name: jjtech-cm
      